-- Phase 1: Create Tables for Intelligent Meal Assistant

-- Table: recipes
-- Stores user-saved recipes, including AI-generated ones.
CREATE TABLE public.recipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  name text not null,
  description text,
  ingredients jsonb,
  instructions jsonb,
  prep_time_minutes integer,
  cook_time_minutes integer,
  servings integer,
  rating smallint check (rating >= 1 and rating <= 5),
  tags text[],
  image_url text,
  source_ai_inputs jsonb
);

-- Table: pantry_items
-- Represents ingredients a user has in their pantry, fridge, or freezer.
CREATE TABLE public.pantry_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  quantity real,
  unit text,
  storage_location text,
  category text,
  expires_at date
);

-- Table: shopping_list_items
-- Represents items on the user's shopping list.
CREATE TABLE public.shopping_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  is_completed boolean not null default false,
  recipe_id bigint references public.recipes(id) on delete set null
);

-- Table: meal_plan_entries
-- Links a recipe to a specific date and time on the user's calendar.
CREATE TABLE public.meal_plan_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  meal_date timestamp with time zone not null,
  meal_type text,
  notification_prefs_mins integer[]
);

-- Phase 2: Add Indexes for Performance
-- Create indexes on all foreign keys and frequently queried columns.
CREATE INDEX ON public.recipes (user_id);
CREATE INDEX ON public.pantry_items (user_id);
CREATE INDEX ON public.pantry_items (category);
CREATE INDEX ON public.shopping_list_items (user_id);
CREATE INDEX ON public.shopping_list_items (is_completed);
CREATE INDEX ON public.meal_plan_entries (user_id);
CREATE INDEX ON public.meal_plan_entries (recipe_id);

-- Phase 3: Enable Row Level Security (RLS)
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pantry_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shopping_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_plan_entries ENABLE ROW LEVEL SECURITY;

-- Phase 4: Create RLS Policies for Data Access
-- Policies for 'recipes' table
CREATE POLICY "Users can manage their own recipes"
ON public.recipes FOR ALL
TO authenticated
USING ((select auth.uid()) = user_id)
WITH CHECK ((select auth.uid()) = user_id);

-- Policies for 'pantry_items' table
CREATE POLICY "Users can manage their own pantry items"
ON public.pantry_items FOR ALL
TO authenticated
USING ((select auth.uid()) = user_id)
WITH CHECK ((select auth.uid()) = user_id);

-- Policies for 'shopping_list_items' table
CREATE POLICY "Users can manage their own shopping list items"
ON public.shopping_list_items FOR ALL
TO authenticated
USING ((select auth.uid()) = user_id)
WITH CHECK ((select auth.uid()) = user_id);

-- Policies for 'meal_plan_entries' table
CREATE POLICY "Users can manage their own meal plan entries"
ON public.meal_plan_entries FOR ALL
TO authenticated
USING ((select auth.uid()) = user_id)
WITH CHECK ((select auth.uid()) = user_id);

-- Phase 5: Create Storage Bucket and Policies
-- Create a private bucket for recipe images.
INSERT INTO storage.buckets (id, name, public)
VALUES ('recipe_images', 'recipe_images', false)
ON CONFLICT (id) DO NOTHING;

-- Add RLS policies for the 'recipe_images' bucket.
-- Users can view their own images.
CREATE POLICY "Users can view their own recipe images"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'recipe_images' AND (storage.foldername(name))[1] = (select auth.uid())::text);

-- Users can upload images into their own folder.
CREATE POLICY "Users can upload to their own recipe folder"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'recipe_images' AND (storage.foldername(name))[1] = (select auth.uid())::text);

-- Users can update their own images.
CREATE POLICY "Users can update their own recipe images"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'recipe_images' AND (storage.foldername(name))[1] = (select auth.uid())::text);

-- Users can delete their own images.
CREATE POLICY "Users can delete their own recipe images"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'recipe_images' AND (storage.foldername(name))[1] = (select auth.uid())::text); 